spring.application.name=exam-service

server.servlet.context-path=/exam-service
server.port=8081

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#config mongoodb
spring.data.mongodb.uri=mongodb://localhost:27017/exam-service